root: true
env:
  browser: true
  es2021: true
  jest/globals: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
  sourceType: module
  project: ./tsconfig.json
plugins:
  - jest
  - '@typescript-eslint'
extends:
  - next
  - next/core-web-vitals
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:storybook/recommended
  - prettier
ignorePatterns: {
    '/lib/**/*',
    # jest.config.jsを除外するため
    '**/*.js',
  }
rules:
  {
    'no-unused-vars': 'off',
    '@typescript-eslint/no-unused-vars':
      [
        'error',
        { 'vars': 'all', 'args': 'after-used', 'ignoreRestSiblings': false },
      ],
  }
